### ISSUE TITLE
Error with mismatched lib versions

### ISSUE THREAD

**Issue by rdavid** [splitice/IPTables.Net#1]
When compiling and using the lib on Ubuntu 14.04 I'm getting the following error: 
```
IPTables.Net(adapter): match "tcp" has version "libxtables.so.10", but "libxtables.so.11" is required.  
```  

When using on Ubuntu 16.04, everything seems to work, can you please point me in the right direction regarding what this error means?

**Comment by splitice** [comment]
Sounds like you have 2 versions of libxtables installed.

**Comment by rdavid** [comment]
Hello,

Probably I miss something. There is my story. I'd like to use your libraries to have C# interface for configuring iptables via C library binding. I've built a test application with IPTables.Net, SystemInteract, SystemInteract.Local C# libraries. It adds single rule to filter table. I used IPTablesLibAdapter for API. I've built libipthelper. Everything is done at Ubuntu 16.04. With minor fixes (supported dport key in string validation) it runs without errors at Ubuntu 16.04. Then I copied .Net libs, .Net app and ipthelper source to Ubuntu 14.04. I re-built ipthelper. Ran it and got following error:
`expert@RSAccessINT:~/IPTablesNetApp$ sudo mono IPTables.Net.App.exe lib                                  
 --dport 443
--
IPTables.Net.Exceptions.IpTablesNetException: IPTCH Error: Unable to capture stdout, errno: 9
  at IPTables.Net.Iptables.NativeLibrary.IptcInterface.GetRuleString (System.String chain, System.IntPtr rule, System.Boolean counters) [0x0006f] in <19f264a6098141429d3abacff0611009>:0 
  at IPTables.Net.Iptables.Adapter.Client.IPTablesLibAdapterClient.ListRules (System.String table) [0x000c2] in <19f264a6098141429d3abacff0611009>:0`

It doesn't happen at Ubuntu 16.04.

What do you think?

Thank you,
David

**Comment by splitice** [comment]
See previous reply. Not a Bug.

**Comment by rdavid** [comment]
@splitice Thanks for your response, I cleaned all other versions, and re-produced 2nd error, as in, the first one was 100% my fault where I had 2 different libs, the 2nd example is reproduced even when using only a single lib version (10), it also seems that the error is regarding STDOUT capture error ? 

Thanks for your fast response and help.

**Comment by rdavid** [comment]
More details. There is a single rule for both 14.04 and 16.04:
```bash
name@domain:~/IPTablesNetApp$ sudo iptables -t filter -L 
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
```

Following code produces two different results:
```C#
            var msg = new StringBuilder();

            try
            {
                msg.Append($"{title}. IP Tables state:{Environment.NewLine}");
                //foreach (var tbl in new string[] {"raw", "filter", "nat", "mangle", "security"})
                foreach (var tbl in new string[] {"filter"})
                {
                    // Two spaces indent.
                    msg.Append($"  {tbl}{Environment.NewLine}");
                    
                    var chains = sys.GetChains(tbl, 4).ToList();
                    if (!chains.Any())
                        msg.Append($"    no chain{Environment.NewLine}");

                    foreach (var chn in chains)
                    {
                        // Four spaces indent.
                        msg.Append($"    {chn.Name}{Environment.NewLine}");
                        if (chn.Rules.Count == 0)
                            msg.Append($"      no rule{Environment.NewLine}");

                        foreach (var rul in chn.Rules)
                        {
                            // Six spaces indent.
                            msg.Append($"      {rul.GetCommand()}{Environment.NewLine}");
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"\n--\n{ex.ToString()}\n--\n".Replace("\n", Environment.NewLine));
            }

            Console.WriteLine(msg);
```
Ubuntu 14.04:
```bash
 --dport 443
--
IPTables.Net.Exceptions.IpTablesNetException: IPTCH Error: Unable to capture stdout, errno: 9
  at IPTables.Net.Iptables.NativeLibrary.IptcInterface.GetRuleString (System.String chain, System.IntPtr rule, System.Boolean counters) [0x0006f] in <186189ec28d24de9931dc2fa86f03021>:0 
  at IPTables.Net.Iptables.Adapter.Client.IPTablesLibAdapterClient.ListRules (System.String table) [0x000c2] in <186189ec28d24de9931dc2fa86f03021>:0 
  at IPTables.Net.Iptables.Adapter.Client.IPTablesLibAdapterClient.IPTables.Net.Netfilter.INetfilterAdapterClient.ListRules (System.String table) [0x00001] in <186189ec28d24de9931dc2fa86f03021>:0 
  at IPTables.Net.Netfilter.NetfilterSystem.GetRules (IPTables.Net.Netfilter.INetfilterAdapterClient client, System.String table) [0x00001] in <186189ec28d24de9931dc2fa86f03021>:0 
  at IPTables.Net.Netfilter.NetfilterSystem.GetChains (IPTables.Net.Netfilter.INetfilterAdapterClient client, System.String table) [0x00001] in <186189ec28d24de9931dc2fa86f03021>:0 
  at IPTables.Net.Netfilter.NetfilterSystem.GetChains (System.String table, System.Int32 ipVersion) [0x0000a] in <186189ec28d24de9931dc2fa86f03021>:0 
  at IPTables.Net.IpTablesSystem.GetChains (System.String table, System.Int32 ipVersion) [0x00001] in <186189ec28d24de9931dc2fa86f03021>:0 
  at IPTables.Net.App.IPTablesNetApp.Print (System.String title, IPTables.Net.IpTablesSystem sys) [0x00052] in <69b7d64c831442819eab578424953d81>:0 
--

Bereshit. IP Tables state:
  filter
```

Ubuntu 16.04:
```bash
Bereshit. IP Tables state:
  filter
    INPUT
      -p tcp --dport 443 -i eth0 -j ACCEPT -m tcp
    FORWARD
      no rule
    OUTPUT
      no rule
```

**Comment by rdavid** [comment]
I've found a root cause for the failure. Our 14.04 is configured with shared memory read-only for security reason.  `ipthelper` uses shared memory for a some reason.
```bash
open("/dev/shm/iph_12340", O_RDWR|O_CREAT|O_TRUNC|O_NOFOLLOW|O_CLOEXEC, 0600) = -1 EROFS (Read-only file system)
dup(1)                                  = 5
dup2(-1, 1)                             = -1 EBADF (Bad file descriptor)
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x2b431ae85000
write(1, " --dport 443", 12 --dport 443)            = 12
lseek(-1, 0, SEEK_SET)                  = -1 EBADF (Bad file descriptor)
read(-1, 0x2b431ee32fde, 1024)          = -1 EBADF (Bad file descriptor)
```

Error handling has a bug. The caller see last read error instead of read only shared memory error. Is it possible not to use shared memory? The library looks as part of `iptables` project, but I didn't find the exact file at `netfilter.org`.

**Comment by splitice** [comment]
Sure that could be patched so it fails at open. Feel free to submit a patch / pull request. 

libxtables used stdout and we redirect it to shared memory rather than manage an extensive patch for libxtables (and every match module).
