### ISSUE TITLE
[Bug] Docs for IpTablesSystem is incorrect

### ISSUE THREAD

**Issue by soroshsabz** [splitice/IPTables.Net#10]
ITNOA

As you can see in https://github.com/splitice/IPTables.Net#deleting-all-defined-rules

Zero arguments contractors exists for `IpTablesSystem` but in real world does not exist

**Comment by splitice** [comment]
Submit a pr if you wish to enhance the documentation

**Comment by soroshsabz** [comment]
@splitice I submit PR for this :)
