### ISSUE TITLE
[Bug] System.DllNotFoundException : Unable to load shared library 'libipthelper'

### ISSUE THREAD

**Issue by soroshsabz** [splitice/IPTables.Net#12]
ITNOA

I have simple test in https://github.com/BSVN/IpTables.Api/pull/9

After I try to run test, I got below exception

```
    System.DllNotFoundException : Unable to load shared library 'libipthelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibipthelper: cannot open shared object file: No such file or directory
```

# Reproduce steps

1. I have a `testEnvironment.json` for docker remote testing
2. I have `Dockerfile.test` for docker base image for remote testing
3. I change environment in Test Explorer (Visual Studio) to Docker
4. I try to run `ListAllRules` test
5. I got exception in Test Explorer as above

How to resolve this problem?

**Comment by splitice** [comment]
Using the lub adapter without the required shared library.
