### ISSUE TITLE
[Bug] GetRules return null

### ISSUE THREAD

**Issue by soroshsabz** [splitice/IPTables.Net#13]
ITNOA

I have code from https://github.com/BSVN/IpTables.Api/pull/9

My code is like below

```
using IPTables.Net;
using IPTables.Net.Iptables;
using IPTables.Net.Iptables.Adapter;
using SystemInteract.Local;

namespace BSN.IpTables.Data.SystemTest
{
    public class Tests
    {
        [SetUp]
        public void Setup()
        {
            ipTablesSystem = new IpTablesSystem(system: new LocalFactory(), tableAdapter: new IPTablesBinaryAdapter());
        }

        [Test]
        public void ListAllRules()
        {
            IpTablesChainSet rules = ipTablesSystem.GetRules(Chain.INPUT, IP_VERSION);
            Assert.Pass();
        }

        private IpTablesSystem ipTablesSystem;
        private const int IP_VERSION = 4;
        public struct Chain
        {
            public const string INPUT = "INPUT";
            public const string OUTPUT = "OUTPUT";
            public const string FORWARD = "FORWARD";
        }
    }
}
```

and in docker system I do not add any rules

I excepted see empty chain set, but I got null result

# Reproduce steps

1. I have a `testEnvironment.json` for docker remote testing
2. I have `Dockerfile.test` for docker base image for remote testing
3. I change environment in Test Explorer (Visual Studio) to Docker
4. I try to run `ListAllRules` test

How to resolve this problem?

thanks

**Comment by splitice** [comment]
Probably getting invalid output from iptables-save https://github.com/splitice/IPTables.Net/blob/032dff9e9adf11be61253916dd4ba99d736129ab/IPTables.Net/Iptables/Adapter/Client/Helper/IPTablesSaveParser.cs#L80

Pr to add useful exception welcome.

**Comment by soroshsabz** [comment]
I suggest add default tables in your library with some constant variable, are you agree with me?

Something like below

```csharp
        public struct Table
        {
            /// <summary>
            /// The filter table is one of the most widely used tables in iptables.
            /// The filter table is used to make decisions about whether to let a packet continue to its intended destination or to deny its request.
            /// In firewall parlance, this is known as “filtering” packets.
            /// This table provides the bulk of functionality that people think of when discussing firewalls.
            /// </summary>
            public const string FILTER = "filter";

            /// <summary>
            /// The nat table is used to implement network address translation rules.
            /// As packets enter the network stack, rules in this table will determine whether
            /// and how to modify the packet’s source or destination addresses in order to impact
            /// the way that the packet and any response traffic are routed.
            ///
            /// This is often used to route packets to networks when direct access is not possible.
            /// </summary>
            public const string NAT = "nat";

            /// <summary>
            /// The mangle table is used to alter the IP headers of the packet in various ways.
            /// For instance, you can adjust the TTL (Time to Live) value of a packet,
            /// either lengthening or shortening the number of valid network hops the packet can sustain.
            /// Other IP headers can be altered in similar ways.
            ///
            /// This table can also place an internal kernel “mark” on the packet for further processing in other tables and by other networking tools.
            /// This mark does not touch the actual packet, but adds the mark to the kernel’s representation of the packet.
            /// </summary>
            public const string MANGLE = "mangle";

            /// <summary>
            /// The iptables firewall is stateful, meaning that packets are evaluated in regards to their relation to previous packets.
            /// The connection tracking features built on top of the netfilter framework allow iptables to view packets
            /// as part of an ongoing connection or session instead of as a stream of discrete, unrelated packets.
            /// The connection tracking logic is usually applied very soon after the packet hits the network interface.
            ///
            /// The raw table has a very narrowly defined function.
            /// Its only purpose is to provide a mechanism for marking packets in order to opt-out of connection tracking.
            /// </summary>
            public const string RAW = "raw";

            /// <summary>
            /// The security table is used to set internal SELinux security context marks on packets,
            /// which will affect how SELinux or other systems that can interpret SELinux security contexts handle the packets.
            /// These marks can be applied on a per-packet or per-connection basis.
            /// </summary>
            public const string SECURITY = "security";
        }
```

**Comment by splitice** [comment]
The only change I would make is to use C# pascal case for the names. And a static class not struct.

**Comment by soroshsabz** [comment]
> The only change I would make is to use C# pascal case for the names. And a static class not struct.

Ok, Did you want I add PR for this?

**Comment by soroshsabz** [comment]
Complete on PR #17

**Comment by soroshsabz** [comment]
> I suggest add default tables in your library with some constant variable, are you agree with me?
> 
> Something like below
> 
> ```cs
>         public struct Table
>         {
>             /// <summary>
>             /// The filter table is one of the most widely used tables in iptables.
>             /// The filter table is used to make decisions about whether to let a packet continue to its intended destination or to deny its request.
>             /// In firewall parlance, this is known as “filtering” packets.
>             /// This table provides the bulk of functionality that people think of when discussing firewalls.
>             /// </summary>
>             public const string FILTER = "filter";
> 
>             /// <summary>
>             /// The nat table is used to implement network address translation rules.
>             /// As packets enter the network stack, rules in this table will determine whether
>             /// and how to modify the packet’s source or destination addresses in order to impact
>             /// the way that the packet and any response traffic are routed.
>             ///
>             /// This is often used to route packets to networks when direct access is not possible.
>             /// </summary>
>             public const string NAT = "nat";
> 
>             /// <summary>
>             /// The mangle table is used to alter the IP headers of the packet in various ways.
>             /// For instance, you can adjust the TTL (Time to Live) value of a packet,
>             /// either lengthening or shortening the number of valid network hops the packet can sustain.
>             /// Other IP headers can be altered in similar ways.
>             ///
>             /// This table can also place an internal kernel “mark” on the packet for further processing in other tables and by other networking tools.
>             /// This mark does not touch the actual packet, but adds the mark to the kernel’s representation of the packet.
>             /// </summary>
>             public const string MANGLE = "mangle";
> 
>             /// <summary>
>             /// The iptables firewall is stateful, meaning that packets are evaluated in regards to their relation to previous packets.
>             /// The connection tracking features built on top of the netfilter framework allow iptables to view packets
>             /// as part of an ongoing connection or session instead of as a stream of discrete, unrelated packets.
>             /// The connection tracking logic is usually applied very soon after the packet hits the network interface.
>             ///
>             /// The raw table has a very narrowly defined function.
>             /// Its only purpose is to provide a mechanism for marking packets in order to opt-out of connection tracking.
>             /// </summary>
>             public const string RAW = "raw";
> 
>             /// <summary>
>             /// The security table is used to set internal SELinux security context marks on packets,
>             /// which will affect how SELinux or other systems that can interpret SELinux security contexts handle the packets.
>             /// These marks can be applied on a per-packet or per-connection basis.
>             /// </summary>
>             public const string SECURITY = "security";
>         }
> ```

resolve in https://github.com/splitice/IPTables.Net/issues/19
