### ISSUE TITLE
[Bug] New nuget packages does not support .NET 6

### ISSUE THREAD

**Issue by soroshsabz** [splitice/IPTables.Net#18]
ITNOA

This is a problem as you can see in https://www.nuget.org/packages/IPTables.Net/0.9.0#supportedframeworks-body-tab, your nuget package support all version above 3.1, but in https://www.nuget.org/packages/IPTables.Net/0.9.1#supportedframeworks-body-tab your nuget package, only support .NET 7

**Comment by soroshsabz** [comment]
I think as a general library we must support all LTS .NET , Did you agree with me?

**Comment by soroshsabz** [comment]
Maybe I can help you to keep support all active ,NET versions (many library and client uses LTS version of .NET, so I think we never disallow LTS version of .NET)

**Comment by splitice** [comment]
Feel free to contribute a PR to expand the CI and spec to include .NET 6 (LTS).

Provided it doesnt add to maintenance requirements down the line its fine.

**Comment by splitice** [comment]
I'd love to also convert this to use github actions, unfortunately the system tests sort of require circleci for now.

**Comment by splitice** [comment]
.NET 8 is now supported
