### ISSUE TITLE
[Bug] Rule does not add correctly

### ISSUE THREAD

**Issue by soroshsabz** [splitice/IPTables.Net#23]
ITNOA

Hi

I have rule like below

```text
-A INPUT -m tcp  --protocol tcp --source 2.2.2.2 --destination 1.1.1.1 --source-port 111 --destination-port 222 --jump DROP
```

I try this rule in `iptables` command in bash and work correctly, but when I try to create rule for this like below

```csharp
IpTablesRule rule = IpTablesRule.Parse($"-A  INPUT  -m tcp--protocol tcp --source 2.2.2.2 --destination 1.1.1.1 --source-port 111 --destination-port 222 --jump DROP", null, chains);
```
and then try to add to system like below

```csharp
 ipTablesSystem = new IpTablesSystem(system: new LocalFactory(), tableAdapter: new IPTablesBinaryAdapter());
 inputChain = ipTablesSystem.GetChain(table: Table.FILTER, chain: Chain.INPUT, ipVersion: (int)IpVersion.V4);
 inputChain.AddRule(rule);
```

No any error rise on system or something like that, but after I try to see system rules with bash (cli) with `iptables -L` I do not see my rules

where is my problem?

**Comment by soroshsabz** [comment]
I ask question about this in SO https://stackoverflow.com/q/76875741/1539100

you can answer it, if you find my problem

thanks

**Comment by splitice** [comment]
Not a bug, you have only added it to the in menory Chain

**Comment by soroshsabz** [comment]
Thanks for response, How to say add to hosted system?

**Comment by soroshsabz** [comment]
@splitice  What is your recommended approach (best practice) to add rule to system?

**Comment by splitice** [comment]
Sync the chain or add the rule using the adapter.

Implementation of a web app is beyond the scope of this library.

**Comment by soroshsabz** [comment]
I add correct adapter and correct system in `ipTableSystem`

Why `AddRule` does not affect my system? and add rule to memory chain?

sorry but I try to understand the spirit of your library API design, so I have many questions ;)

Why below chain in memory?

```csharp
 inputChain = ipTablesSystem.GetChain(table: Table.FILTER, chain: Chain.INPUT, ipVersion: (int)IpVersion.V4);
```

**Comment by splitice** [comment]
Take a look at sync in the readme or if you don't like that look at how sync does its job (adding and removing rules).

**Comment by soroshsabz** [comment]
@splitice README does not update, `Sync` does not get chain.

**Comment by splitice** [comment]
Unless you apply your changes to the system it's all in memory.

Look at the sync Api. Look at the tests if you need more I think.
