### ISSUE TITLE
Add support for nftables

### ISSUE THREAD

**Issue by soroshsabz** [splitice/IPTables.Net#26]
ITNOA

I think it is good to add support for nftables

As you can see in [RedHat](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/configuring_firewalls_and_packet_filters/getting-started-with-nftables_firewall-packet-filters#assembly_migrating-from-iptables-to-nftables_getting-started-with-nftables)

**nftables is successor of iptables**

**Comment by splitice** [comment]
It was attempted in the past. Abandoned due to no users and little overlap.
