### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by gerald-dotcom** [splitice/IPTables.Net#4]
Matt,

I don't find Issue option in your p0f-ssl lib therefore opening issue on behalf of p0f-ssl lib in here. 

The lib complies fine and build also okay but when I initialize p0f, it prints Segmentation fault (core dumped)

p0fSSL -d -f /etc/p0f-ssl/p0f.fp -s /var/run/p0fSSL.sock
--- p0f 3.07b by Michal Zalewski <lcamtuf@coredump.cx> ---

[!] Consider specifying -u in daemon mode (see README).
[+] Closed 1 file descriptor.
[+] Loaded 406 signatures from '/etc/p0f-ssl/p0f.fp'.
Segmentation fault (core dumped)

Please let me know what should I do for this!

Thanks,
Cornelius

**Comment by splitice** [comment]
Investigate, Fork, Fix. That project has not been under development for years (although it was working when I ceased development).

**Comment by gerald-dotcom** [comment]
I absolutely investigated over 2 weeks and found nothing wrong with the repo. I even tried the repo you forked originally, it didn't worked either, empty SSL values.

Would you like to share the env details which you deployed this?

If not, I'm willing to pay for a fix.

I must say I'm a horrible C programmer, my main stack is C++


________________________________

**Comment by splitice** [comment]
Honestly gerald I doubt either project would be super useful today. It's quite out of date, to be particularly useful today support for newer TLS versions etc would be needed.

While I suppose I could look into this for you I'd suggest making sure this is actually fit for purpose. Alot has happened in 5 years and this software has gotten very stale. Not trying to be pessimistic, just trying to set realistic expectations.

Feel free to contact me at mheard [at] x4b [....] net if you still want to pursue something.

**Comment by gerald-dotcom** [comment]
@splitice I've re-implemented all this in C++ with DPDK. Absolutely, faster than libpcap and will connect with you if I need anything else. Thanks for the help anyway!
