### ISSUE TITLE
Port to netcore 3.1

### ISSUE THREAD

**Issue by pearl2201** [splitice/IPTables.Net#5]
I am trying to make a port scanner detector and block any suspecious ip in net core 3.1.
I really want to use this library to sync blocked ips but this library is built base on Net 4.6...

**Comment by splitice** [comment]
If you submit a Pull Request that builds both the Nuget package & runs the test on both I will accept it.

**Comment by splitice** [comment]
I am tempted to close this. However I'll leave it open in the hopes of external contribution.

I am not going to be doing this at this stage. Although that said it's likely possible in the future. We use IPTables.Net exclusively on Linux (of course) and in a console application so netcore makes sense. Simply put though, it's not necessary for us at this as we have no issues with the current platform and we have higher priority tickets.

I don't expect it would be a whole lot of work (primarily updating the CI build scripts & solution) so it would make a good first contribution.

**Comment by splitice** [comment]
Due to hitting a conflicting requirement I ended up doing this upgrade.

dotnetcore 3.1 for now.
