### ISSUE TITLE
Provide ipthelper binaries in releases

### ISSUE THREAD

**Issue by jjxtra** [splitice/IPTables.Net#7]
It would be wonderful if you could provide x86 and x64 versions of the ipthelper library, that would avoid everyone having to figure out how to build it.

**Comment by splitice** [comment]
Library is linked with specific versions of multiple libraries that can not be made static. This combined with the fact that libxtables is a bit of a messy library and our implementation requires a few hacks means that it's difficult to acheive. Back when I was developing the initial library I considered building a libxtables alternative (that compatibly as libxtables as a drop-in e.g via LD PRELOAD)

I welcome any PR that:
1. modernizes the build process for libiptch
2. goes onto CI build common distributions (Ubuntu, Debian & Centos).

For now however both of these are beyond my scope.

**Comment by splitice** [comment]
Closed due to lack of op pr.
